# Generated by Django 4.2.7 on 2023-12-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nickname',
            new_name='username',
        ),
    ]
