# Generated by Django 4.2.7 on 2024-01-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0002_alter_redacao_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='redacao_corrigida',
            field=models.TextField(blank=True, null=True),
        ),
    ]
