# Generated by Django 4.2.7 on 2023-12-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0002_rename_nickname_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
    ]
