# Generated by Django 5.0 on 2023-12-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0003_rename_senha_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
