# Generated by Django 5.0.1 on 2024-01-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0004_alter_redacao_data_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='redacao',
            name='usuario',
        ),
    ]
