# Generated by Django 4.2.7 on 2024-01-10 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
