# Generated by Django 4.2.7 on 2024-01-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacao',
            name='erros_redacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
