# Generated by Django 4.2.7 on 2024-01-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EscritaExemplar', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
